### ISSUE TITLE
UPnP Support?

### ISSUE THREAD

**Issue by Tazintosh** [cloudfs/ftp-cloudfs#45]
Hi Juan,

Do you plan to support UPnP.
I've a close friend that needs to connect to my ftpcloud-fs server in passive mode to make is own backups on my storage.
Actually, I can see the incoming connection of him is working, but we have a time-out so he can never have a file listing: “Passive data channel timeout”

If he connects through my VPN, it's working fine, so I bet on the passive ports.
UPnP would give a great flexibility. What do you think?

**Comment by reidrac** [comment]
I'm sorry it's very unlikely we can support this, mainly because the ftp support is provided by pyftpdlib.

If the library supported UPnP, we could expose that functionality in the FTP server. I would suggest you to use [sftp-cloudfs](https://github.com/Memset/sftpcloudfs); that is built on top of the ftp-cloudfs fs abstraction.

It uses only one port that can be easily setup via any firewall (and also: encryption!).
