### ISSUE TITLE
Rename of DLO manifest object isn't rename segments

### ISSUE THREAD

**Issue by vills** [cloudfs/ftp-cloudfs#54]
After upload object with bigger size than `split-large-files` setting, we got DLO-manifest + segments in path like 'OBJECT_NAME.part/XXXXXX'. FTP-protocol allow us to rename objects and it works fine with object less in size than `split-large-files`. But renaming DLO-manifest isn't rename its segments (and that 'OBJECT_NAME.part' "directory" hidden from ftp-listing if `hide-part-dir = yes`.

So in some workflows we got interesting results. For example:
- upload object '1.file' larger than `split-large-file`;
- rename '1.file' to '1.file.bak';
- upload '1.file' with new content (larger than `split-large-file` of course);
- now both '1.file' and '1.file.bak' point to same '.part' "directory" in 'X-Object-Manifest' header (and data of object corrupted as well).

Conclusion: segments objects should be also renamed with manifest-object.

**Comment by reidrac** [comment]
When that functionality was added in version `0.26` we didn't want to rename the parts because it is really a copy of each part, and it would be too expensive.

I see the problem of a rename and the uploading another large file that causes a collision with the parts. We could fix that case by creating a different `.part` directory, but we won't be renaming the parts.

I'll think if we can close this bug as won't fix and open a new one describing the collision problem after the rename.

**Comment by reidrac** [comment]
Created #56 to deal with this issue.

Thanks for your report.
